Update jsonvalue.yml

diff --git a/.github/workflows/jsonvalue.yml b/.github/workflows/jsonvalue.yml
--- a/.github/workflows/jsonvalue.yml
+++ b/.github/workflows/jsonvalue.yml
@@ -8,7 +8,7 @@ jobs:
     runs-on: ubuntu-latest
     steps:
     - name: Check if JSON file exists
-      run: test -f NSI.json && echo "File exists" || echo "File not found"
+      run: test -f /job_dependencies/nsivalue.json && echo "File exists" || echo "File not found"
     - name: Update JSON file with secrets
       run: |
         jq '.PASSWORD = "${{ secrets.DOCKER_USERNAME }}" | .USERNAME = "${{ secrets.DOCKER_PASSWORD }}"' ./job_dependencies/nsivalue.json > /tmp/updated_nsivalue.json && mv /tmp/updated_nsivalue.json ./job_dependencies/nsivalue.json
